apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: nlw-passin
  namespace: argocd

spec:
  project: default
  source:
   repoURL: https://github.com/lucianoRSouzaa/nlw-devops
   targetRevision: HEAD
   path: deploy
  destination:
   server: https://kubernetes.default.svc
  syncPolicy:
   automated:
    prune: true