name: CI

# quando tiver um push na branch main, ele vai rodar o job build-and-push
on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: 'Build and push'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4  # step já pronto (como se fosse uma lib)

    - name: Generate sha
      id: generate_sha
      # linha 1 - pega os 7 primeiros caracteres do sha (hash) do commit
      # linha 2 - cria variável sha que recebe o conteúdo de SHA
      # e escreve no arquivo $GITHUB_OUTPUT
      run: |
        SHA=$(echo $GITHUB_SHA | head -c7)
        echo "sha=${SHA}" >> $GITHUB_OUTPUT
        
    - name: Build docker image
      # gera a imagem docker com o nome nlw.service.passin e a tag vinda do generate_sha
      run: docker build -t luciano955/nlw.service.passin:${{ steps.generate_sha.outputs.sha }} .

    # loga no dockerhub
    - name: Log into the container registry
      uses: docker/login-action@v3
      # with: passa os parâmetros para a action
      # secrets - fica lá no github, em settings, security, secrets and variables
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # pusha a imagem para o dockerhub
    - name: Push image
      run: |
        docker push luciano955/nlw.service.passin:${{ steps.generate_sha.outputs.sha }}
        docker tag luciano955/nlw.service.passin:${{ steps.generate_sha.outputs.sha }} luciano955/nlw.service.passin:latest
        docker push luciano955/nlw.service.passin:latest

    - name: Update image tag
      uses: fjogeleit/yaml-update-action@main
      with:
        branch: main
        valueFile: 'api/deploy/values.yaml'
        propertyPath: 'image.tag'
        value: ${{ steps.generate_sha.outputs.sha }}
        commitChange: true
        message: "new: Update tag in values helm"